# Adapted from: https://github.com/ptrcnull/dotfiles/blob/master/config/starship.toml
add_newline = true
format = """
$env_var\
$username\
$hostname\
$directory\

$git_branch\
$git_commit\
$git_state\
$git_status\

$python\

$character"""

right_format ="""
$battery"""

palette = "catppuccin_macchiato"


[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
threshold = 99


[env_var.CUSTOM_PROMPT_TAG]
format = "[$env_value]($style) "
style = "green bold"

[username]
format = "[$user]($style)@"

[hostname]
format = "[$hostname]($style) "

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 3

[git_status]
format = "$ahead_behind$conflicted$stashed$deleted$renamed$staged$modified$untracked"
ahead = "[⇡${count}](yellow) "
behind = "[⇣${count}](yellow) "
stashed = "[*${count}](yellow) "
deleted = "[x${count}](red) "
staged = "[+${count}](yellow) "
modified = "[!${count}](yellow) "
untracked = "[?${count}](cyan) "

[python]
format = 'with [${symbol}${pyenv_prefix}($virtualenv )]($style)'
detect_files = []
detect_extensions = []

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
