#!/bin/sh

escape() {
	printf "%s" "$1" | sed 's#\\#\\\\#g'
}

if [ "$BUFFER" = "$SENDER" ]; then
    title="[$BUFFER]"
else
    title="[$BUFFER] $SENDER"
fi

focus=$(xdotool getwindowfocus getwindowname |grep -c senpai)

if [ "$focus" -eq 0 ]; then
	notify-send "$title" "$(escape "$MESSAGE")"
fi
